{{- if and .Values.tavily.apiKey (not .Values.tavily.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langgraph-ollama.fullname" . }}-secret
  labels:
    {{- include "langgraph-ollama.labels" . | nindent 4 }}
type: Opaque
stringData:
  TAVILY_API_KEY: {{ .Values.tavily.apiKey | quote }}
{{- end }}
